- name: Install Docker and configure komga container
  hosts: rpi_servers
  become: true

  tasks:
    - name: Include variables from config_paths.yml
      include_vars:
        file: config_paths.yml
     
    - name: Include usernames from owners.yml
      include_vars:
        file: owners.yml
    

    - name: Upadte Package list
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt: 
        name: "{{ item }}"
        state: present
      with_items:
        - containerd

    - name: Install docker
      apt:
        name: docker.io
        state: present
      become: true

    - name: Ensuer docker service is running
      service:
        name: docker
        state: started
      become: true

    - name: Install Python Docker Library
      pip:
        name: docker
        state: present

    - name: Create directory for komga
      file:
        path: "{{ komga_main_path }}"
        state: directory
        mode: '0775'
        owner: "{{ username }}"
        group: "{{ groupname }}"
      become: true

    - name: Create directory for komga config
      file:
        path: "{{ komga_config_path }}"
        state: directory
        mode: '0775'
        owner: "{{ username }}"
        group: "{{ groupname }}"
      become: true
    
    - name: Create directory for komga data
      file:
        path: "{{ komga_data_path }}"
        state: directory
        mode: '0775'
        owner: "{{ username }}"
        group: "{{ groupname }}"
      become: true

    - name: Pull docker Image
      docker_image:
        name: gotson/komga
        source: pull
        state: present
    
    - name: Create Komga container
      docker_container:
        name: komga
        user: "1000:1000"
        ports:
          - "25600:25600"
        volumes:
          - "{{ komga_config_path }}:/config"
          - "{{ komga_data_path }}:/data"
        restart_policy: unless-stopped
        image: gotson/komga
      become: true
        
